#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

csv_file = sys.argv[1]
f = open(csv_file)

lines = [line.strip() for line in open(csv_file)]

f.close()

images = lines[2].split(',')
item_for_images = {}

for i in range(3,len(lines)):
    items = lines[i].split(',')
    if not items or len(items) <= 0:
        continue
    for index, item in enumerate(items):
        if not item or len(item) <= 0:
            continue
        if index in item_for_images:
            item_for_images[index].append(item)
        else:
            item_for_images[index] = [item]

for index, image in enumerate(images):
    if not image or len(image) <= 0:
        continue
    l = [image]
    if index in item_for_images:
        l.extend(item_for_images[index])
    print " ".join(l)
