#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
输入文件格式：
<文件名> 货号 货号 ...
.
.
.
"""

import sys

timeset_id = sys.argv[2]

f = open(sys.argv[1], 'r')

for line in f:
    items = line.strip().split(' ')
    filename = """%s.jpg""" % items.pop(0)
    print """INSERT INTO model (filename, timeset_id) VALUES ("%s", %s);""" % (filename, timeset_id)
    for item in items:
        print """INSERT INTO model_item (model_id, item_id) SELECT id,"%s" FROM model WHERE filename="%s";""" % (item, filename)

f.close()

