#!/bin/bash

echo 'Checking/Creating directory structure...'
[ -d app/cache ]   || mkdir -p app/cache
[ -d app/logs ]    || mkdir -p app/logs
[ -d web/media ]   || mkdir -p web/media
[ -d web/uploads ] || mkdir -p web/uploads
[ -d web/avatar ]  || mkdir -p web/avatar

echo 'Emptying app/cache/* and app/logs/* ...'
rm -rf app/cache/*
rm -rf app/logs/*

echo 'Setting acl...'
if [[ ${OSTYPE//[0-9.]/} == 'linux-gnu' ]]; then
    sudo setfacl -R -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs web/media web/uploads web/avatar
    sudo setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs web/media web/uploads web/avatar
elif [[ ${OSTYPE//[0-9.]/} == 'darwin' ]]; then
    sudo /bin/chmod +a "_www allow delete,write,append,file_inherit,directory_inherit" app/cache app/logs web/media web/uploads web/avatar
    sudo /bin/chmod +a "`whoami` allow delete,write,append,file_inherit,directory_inherit" app/cache app/logs web/media web/uploads web/avatar
else
    echo Operation System ${OSTYPE} not supported
    exit
fi

echo 'Done.'
