#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import tempfile
import os
import subprocess

CODE_TEMPLATE = """#include <stdio.h>
int main()
{
    return sizeof(%s);
}"""

if len(sys.argv) < 2:
    sys.stderr.write("""Usage: %s "\033[00;33m<typename>\033[00m"\n""" % os.path.basename(__file__))
    sys.exit(1)

input = sys.argv[1]

input_file  = tempfile.NamedTemporaryFile(suffix=".c", delete=False)

input_file.write(CODE_TEMPLATE % input)
input_file.close()

output_file = tempfile.NamedTemporaryFile(delete=False)
output_file.close()

if subprocess.call(["cc", "-O3", input_file.name, "-o", output_file.name]) == 0:
    size = subprocess.call(output_file.name)
    print """sizeof(%s) is %lu""" % (input, size)
    os.unlink(output_file.name)

os.unlink(input_file.name)
